### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by fmoghaddampoor** [daemontus/VuforiaLibGDX#3]
When I´m running your code with android studio, I get several errors, some of them where because of the Vuforia library was not inside where I have solved it and some were for Gradles.
Could you please once tell how to setup the project with android studio, thanks a lot I'm beginner with android and libgdx , Its a new world for me.

**Comment by daemontus** [comment]
Well, first of all, I recommend checking out the version which is based on the older Vuforia and LibGDX (https://github.com/daemontus/VuforiaLibGDX/tree/old) - these older versions are directly included in the project as jar files (and no NDK needed or fiddling with Gradle files), therefore the overall setup should be much easier. As soon as you confirm that you can build and run those, you can try using the latest versions, which are a bit harder to set up.

Anyway, you probably have problems with the Vuforia library, since the LibGDX is quite conventional. Vuforia assumes you have Android NDK installed, so first I would make sure of that - It can be actually installed using the SDK manager (see http://tools.android.com/tech-docs/android-ndk-preview), although if your are running on OS X, there are some bugs involved (you have to copy the toolchains from the actual NDK - let me know if you get some weird errors regarding missing NDK toolchains). Then you need to download Vuforia, unzip it and put it somewhere on your hard drive - some details are in the set up guide https://developer.vuforia.com/library/articles/Solution/Installing-the-Vuforia-Android-SDK - Finally, you need to update the VUFORIA_SDK_DIR variable in the app/build.gradle file to point to the location where you unzipped the library (although from what you wrote, I'm assuming you already did this). Also maybe try running some of the pure Vuforia examples to verify that the library is correctly set up.

If this still doesn't work, please try giving the specific error you are getting, otherwise I have no idea what to focus on :)

**Comment by fmoghaddampoor** [comment]
Bro, Thanks a lot, Its so cool. The old project is working really.

**Comment by daemontus** [comment]
No problem, but keep in mind that you might not be able to generate recognition targets that are compatible with these old versions using the Vuforia developer portal. They changed the format a bit, so the new files they generate now aren't actually backward compatible. Maybe there is still a way to produce the legacy format somehow, but I haven't seen such setting anywhere.

**Comment by fmoghaddampoor** [comment]
Ummm thats a problem, then do you think if there is a way to use vuforia 5.5 with this old one project that is working. What about your new code. I have seen in the recent sdk of vuforia, there is feature detection. Is it working only with wifi on or also it works without it?

**Comment by daemontus** [comment]
The new code is essentially the same, it is just updated a little bit so that it actually uses the latest Vuforia . In other words: The actual changes in the code are minimal (mostly pacakge name changes), the only thing that really changed are the gradle.build files since the new Vuforia is included differently. I just suggested that you first try running the old code so that we eliminated some technical problems on your side and sort-of confirmed that the problem is indeed the new Vuforia (or LibGDX, but I doubt that).
Anyway, could you be more specific regarding the problems you are having with the latest branch? Some error messages or something?

**Comment by fmoghaddampoor** [comment]
I have downloaded your new code, then added vuforai.jar and also its engine. by changing the engine from so type file to jar file (making the folder containing the so file first zip and then changed the extension to jar ), copied the vuforia and the engine to the folder lib in your library, imported the root folder with android studio. then i change the android style to project files style and then found the libraries are in place. I right clicked on the project and went to open module settings, then in app tab i opened dependencies and added the new vuforia and its engine to the dependency list.Also I have checked NDK existed.I pressed ok.
i get this error about the gradles which seems I can not find a solution for it:

Error:(53, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'VuforiaLibGDX-master' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
However I´m still wondering what is tool chain? cause latest vuforia samples were working like the procedure I told here. I´m using windows 10 by the way.
Also I have noticed in import places vuforia was not found however I have added it to the dependencies.
import com.**vuforia**.Matrix44F;

my grades are like this:
build.grade project:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}
```

build.grade :Module

```
apply plugin: 'com.android.application'

def VUFORIA_SDK_DIR = '/Users/daemontus/Library/Vuforia'
def NATIVE_LIB_DIR = 'build/lib'
def JAR_DIR = 'build/java/vuforia'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    sourceSets.main {
        jni.srcDirs = []
        jniLibs.srcDirs = ["$VUFORIA_SDK_DIR/$NATIVE_LIB_DIR/", "lib/"]
    }

    defaultConfig {
        applicationId "com.github.daemontus.renderer"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }

    archivesBaseName = rootProject.projectDir.getName()

    buildTypes {
        release {
            minifyEnabled false
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
        debug {
            minifyEnabled false
            debuggable true
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
    }
}

repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

ext {
    gdxVersion = '1.9.3'
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.+'
    compile "com.badlogicgames.gdx:gdx:$gdxVersion" compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion" compile files('lib/vEngine.jar')
    compile files('lib/Vuforia.jar')
    compile files('lib/vEngine.jar')
}

```

**Comment by fmoghaddampoor** [comment]
I have also changed my gradle like this but still vuforia can not be found:

```
apply plugin: 'com.android.application'
def VUFORIA_SDK_DIR = 'C:\\Dev\\vuforia-sdk-android-5-5-9'
def NATIVE_LIB_DIR = 'build/lib'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    sourceSets.main {
        jni.srcDirs = []
        jniLibs.srcDirs = ["$VUFORIA_SDK_DIR/$NATIVE_LIB_DIR/", "lib/"]
    }

    defaultConfig {
        applicationId "com.github.daemontus.renderer"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }

    archivesBaseName = rootProject.projectDir.getName()

    buildTypes {
        release {
            minifyEnabled false
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
        debug {
            minifyEnabled false
            debuggable true
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
    }
}

repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

ext {
    gdxVersion = '1.9.3'
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.+'
    compile fileTree(include: '*.jar', dir: 'libs')
    compile files('libs/vuforia.jar')
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
}

I dont have however The previous Error. The error is :
Error:(16, 19) error: package com.vuforia does not exist

I think the vuforia.so is not compiled in this way.
```

**Comment by fmoghaddampoor** [comment]
At the end I have found My problem but I get black image:

I should have listened to complete recommendations. They are just right.

I changed the gradle file like this:

```
apply plugin: 'com.android.application'
def VUFORIA_SDK_DIR = 'C:\\Dev\\vuforia-sdk-android-5-5-9'
def NATIVE_LIB_DIR = 'build/lib'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    sourceSets.main {
        jni.srcDirs = []
        jniLibs.srcDirs = ["$VUFORIA_SDK_DIR/$NATIVE_LIB_DIR/", "lib/"]
    }

    defaultConfig {
        applicationId "com.github.daemontus.renderer"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }

    archivesBaseName = rootProject.projectDir.getName()

    buildTypes {
        release {
            minifyEnabled false
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
        debug {
            minifyEnabled false
            debuggable true
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
    }
}

repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

ext {
    gdxVersion = '1.9.3'
}

dependencies {
    compile 'com.android.support:appcompat-v7:23.+'
    compile fileTree(include: '*.jar', dir: 'lib')
    compile files('lib/vuforia.jar')
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
}
```

its working, but when it starts it just shows black!

**Comment by fmoghaddampoor** [comment]
Bro At the end it worked But it took a lot more time than the old project. Do you know whats the problem? When I choose the middle button for my tablet and bring the softwares running on my tablet and click the software again to resume, the camera works and the black screen goes. it seems there should be a refresh function to call. I need to learn more about libgdx.

**Comment by daemontus** [comment]
Apologies, I had exams and no time to respond. Glad you worked it out - at least partially - If I understand you correctly, you are saying that the screen stays black after you pause and resume the app, right? (It's possible it's a bug in my code - I took it from another app of mine and I might have forgotten to copy something)

**Comment by fmoghaddampoor** [comment]
Actually when i run it it stays black until you pause and you resume it . Yes.I don't know if there is a code to pause and resume it programmatically to turn this bug over.

**Comment by daemontus** [comment]
Well, that is indeed really weird - what Android version are you testing at? Can you reproduce it on multiple devices?

**Comment by xeoshow** [comment]
Great project!
Can iOS platform be supported and how? Thanks!

**Comment by daemontus** [comment]
I am not sure if I can answer that, but hey, I can try!
The thing is, libGDX support on iOS has been on a crossroads recently thanks to RoboVM shutdown (http://www.badlogicgames.com/wordpress/?p=3925) and I have no idea what the current status is.
If you want to use RoboVM with Vuforia, I think you would need to write your own bindings (https://news.ycombinator.com/item?id=7578974 - or maybe they are done somewhere and I just haven't found them), but have never tried that, so I have no idea how complicated that is.

**Comment by xeoshow** [comment]
Thanks for kind reply!
For libgdx, there is already a fork of RoboVM which can be used freely, I will investigate the link you provided and feedback when get results!~

**Comment by daemontus** [comment]
Closed due to inactivity
