### ISSUE TITLE
Erroneous matrix parameters for landscape mode

### ISSUE THREAD

**Issue by boulabiar** [daemontus/VuforiaLibGDX#7]
VuforiaLibGDX works perfectly on Portrait mode.
In landscape mode the matrix parameters looks like they are inverted for x and y and the model is inverted.

you can activate Vuforia in Landscape mode using
mActivity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
(added in initAR function inside AppSession and commenting other lines)

**Comment by daemontus** [comment]
Closed due to deprecation (#4)
